#!/usr/bin/env python3
"""Bake a binary file into a C header as a byte array.

Used for the things the setup screen needs before any game data exists: it runs
on a bare exe with nothing beside it, so its music, its sound effects and (once
converted) the splash images cannot be loose files. Everything it touches has
to already be inside the binary.

This is only ever pointed at OUR OWN content -- the setup audio under Setup/,
authored for this project. Retail game data stays out of the repo and out of
the exe; see .gitignore.

Usage:
    bin2c.py <input> <output.h> <symbol>

Produces:
    const unsigned char <symbol>[] = { ... };
    const unsigned int  <symbol>_len = N;
"""
import sys
import os


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2

    src, dst, sym = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(src, "rb").read()

    os.makedirs(os.path.dirname(os.path.abspath(dst)), exist_ok=True)

    with open(dst, "w", newline="\n") as f:
        f.write(f"/* Generated by tools/bin2c.py from {os.path.basename(src)}."
                f" Do not edit. */\n")
        f.write(f"#ifndef ROBOX_BIN2C_{sym.upper()}\n")
        f.write(f"#define ROBOX_BIN2C_{sym.upper()}\n\n")
        f.write(f"const unsigned char {sym}[] = {{\n")
        for i in range(0, len(data), 16):
            row = ",".join(f"0x{b:02x}" for b in data[i:i + 16])
            f.write(f"    {row},\n")
        f.write("};\n")
        f.write(f"const unsigned int {sym}_len = {len(data)}u;\n\n")
        f.write("#endif\n")

    print(f"{dst}: {len(data)} bytes -> {sym}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
