#!/usr/bin/env python3
"""Generate sdk/android_asset_manifest.h -- the list of files to extract from
the APK on first launch.

Android's native AAssetDir API cannot reliably enumerate subdirectories, so the
list of packaged data files has to be baked in at build time. This walks the
same set of paths that android/app/build.gradle's copyRoboxData task stages,
and must stay in sync with it.

Run from the repo root:
    python tools/gen_android_manifest.py
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, 'sdk', 'android_asset_manifest.h')

# (source dir relative to repo, prefix inside the APK assets namespace)
TREES = [
    ('Assets', 'Assets'),
    ('build/mods', 'mods'),
]
FILES = ['Robox USA.dol']


def collect():
    out = []
    for src, prefix in TREES:
        base = os.path.join(REPO, src)
        if not os.path.isdir(base):
            print(f'  warning: {src} not found, skipping', file=sys.stderr)
            continue
        for dirpath, _dirnames, filenames in os.walk(base):
            for fn in sorted(filenames):
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, base).replace(os.sep, '/')
                out.append(f'{prefix}/{rel}')
    for f in FILES:
        if os.path.isfile(os.path.join(REPO, f)):
            out.append(f)
        else:
            print(f'  warning: {f} not found, skipping', file=sys.stderr)
    return sorted(out)


def main():
    assets = collect()
    total = 0
    for a in assets:
        for src, prefix in TREES:
            if a.startswith(prefix + '/'):
                p = os.path.join(REPO, src, a[len(prefix) + 1:])
                break
        else:
            p = os.path.join(REPO, a)
        try:
            total += os.path.getsize(p)
        except OSError:
            pass

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// GENERATED by tools/gen_android_manifest.py -- DO NOT EDIT\n')
        f.write('//\n')
        f.write('// Files extracted from the APK to internal storage on first launch.\n')
        f.write('// Android cannot enumerate asset subdirectories from native code, so\n')
        f.write('// the list is baked in. Must stay in sync with the copyRoboxData task\n')
        f.write('// in android/app/build.gradle.\n')
        f.write(f'//\n// {len(assets)} files, {total / 1024.0 / 1024.0:.1f} MiB total\n\n')
        f.write('#pragma once\n\n')
        f.write('static const char *k_assets[] = {\n')
        for a in assets:
            f.write('    "%s",\n' % a.replace('\\', '\\\\').replace('"', '\\"'))
        f.write('};\n\n')
        f.write('static const int k_num_assets = (int)(sizeof k_assets / sizeof k_assets[0]);\n')

    print(f'wrote {OUT}')
    print(f'  {len(assets)} files, {total / 1024.0 / 1024.0:.1f} MiB')


if __name__ == '__main__':
    main()
